# -*- coding: utf-8 -*-
"""xfu_ds121_hw1_final.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/15MX5AOnaIDOLtAi8BzE5i1SRwWra9Msv

#DS 121 Spring 2023 - Homework 1
## Due February 3 at 8pm

This assignment contains __10 questions__ worth __80 points__. You must submit your solution on [Gradescope](https://www.gradescope.com/courses/495963). Make sure that all cells are visible before you export to PDF and submit on Gradescope using [these instructions](https://help.gradescope.com/article/ccbpppziu9#submitting_a_pdf). Review your file after uploading to check that it is legible and complete.

You must follow the Collaboration Policy in the course syllabus while working on this assignment. For each question, make sure to acknowledge any classmates you collaborated with or sources you used (aside from the textbooks and lecture notes).

## Part A: Solve by hand

You must solve questions in this part by hand (though you can check your work with a computer if you want). You may type in your responses using Markdown and LaTeX formatting of equations, or you may scan a photo of a handwritten solution. Illegible solutions cannot be graded.

Remember to __explain your reasoning!__ Simply providing the answer without any explanation will result in 0 credit.

### Question 1 (10 points)
 Write $y = \begin{bmatrix} 1 \\ 3\\ -1 \end{bmatrix}$ as a linear combination of:

$x_1 = \begin{bmatrix} 1 \\ 0 \\ 0 \end{bmatrix}$, $x_2 = \begin{bmatrix} 2 \\ -2 \\ 1 \end{bmatrix}$, $x_3 = \begin{bmatrix} 2 \\ 0 \\ 4 \end{bmatrix}$.

**Your response:**

Linear combination condition:

$y = a x_1 + b x_2 + c x_3$


Expanding this equation out, we get the system of equations:

$\begin{bmatrix} 1 \ 3 \ -1 \end{bmatrix} = a \begin{bmatrix} 1 \ 0 \ 0 \end{bmatrix} + b \begin{bmatrix} 2 \ -2 \ 1 \end{bmatrix} + c \begin{bmatrix} 2 \ 0 \ 4 \end{bmatrix}$

This can be written in matrix form as

$\begin{bmatrix} 1 \ 3 \ -1 \end{bmatrix} = \begin{bmatrix} 1 & 2 & 2 \ 0 & -2 & 0 \ 0 & 1 & 4 \end{bmatrix} \begin{bmatrix} a \ b \ c \end{bmatrix}$

Solving this system of equations for $a$, $b$, and $c$, we find:

$a = -1, b = 1, c = -1$

So, $y = \begin{bmatrix} 1 \ 3\ -1 \end{bmatrix}$ can be written as a linear combination of $x_1$, $x_2$, and $x_3$ as $y = -x_1 + x_2 -x_3$

**Collaborators and resources:**

Not applicable

###Question 2 (16 points)

Are the following set of vectors linearly independent? Explain your reasoning.

a. $x_1 = \begin{bmatrix} 1 \\ 4 \\ 3 \end{bmatrix}$, $x_2 = \begin{bmatrix} 2 \\ 1 \\ 0 \end{bmatrix}$, $x_3 = \begin{bmatrix} 4\\ 9 \\6 \end{bmatrix}$

b. $x_1 = \begin{bmatrix} 1 \\ 2 \\ -3 \\ 4 \end{bmatrix}$, $x_2 = \begin{bmatrix} 1 \\ 1 \\ 0 \\ 2 \end{bmatrix}$,$x_3 = \begin{bmatrix} -1 \\ -2 \\ 1 \\ 1 \end{bmatrix}$

c. $x_1 = \begin{bmatrix} 1 \\ 0 \\ 1 \end{bmatrix}$, $x_2 = \begin{bmatrix} 1 \\ 1 \\ 0 \end{bmatrix}$, $x_3 = \begin{bmatrix} 0 \\ 1 \\ -1 \end{bmatrix}$

d. $x_1 = \begin{bmatrix} 1 \\ 3 \end{bmatrix}$, $x_2 = \begin{bmatrix} 2 \\ 2 \end{bmatrix}$, $x_3 = \begin{bmatrix} 0 \\ 1 \end{bmatrix}$

**Your response:**

a. Assume that the set of vectors is linearly dependent, meaning that at least one of the vectors can be expressed as a linear combination of the others. We can write this as:

$a x_1 + b x_2 + c x_3 = 0$

where $a$, $b$, and $c$ are the coefficients. This can be written as:

$\begin{bmatrix} 1 & 2 & 4 \ 4 & 1 & 9 \ 3 & 0 & 6 \end{bmatrix} \begin{bmatrix} a \ b \ c \end{bmatrix} = \begin{bmatrix} 0 \ 0 \ 0 \end{bmatrix}$

We can solve this system of equations by finding the inverse of the matrix, if it exists. But in this case, we can see that the matrix is not invertible, which means that the only solution to this system of equations is the trivial solution (all variables equal to 0). This means that the set of vectors is linearly independent.

So, the set of vectors {$x_1$, $x_2$, $x_3$} is linearly independent.







b. The matrix formed by the given vectors is:
$\begin{bmatrix} 1 & 1 & -1 \ 2 & 1 & -2 \ -3 & 0 & 1 \ 4 & 2 & 1 \end{bmatrix}$

We can perform row echelon form on this matrix, which gives us:
$\begin{bmatrix} 1 & 1 & -1 \ 0 & -1 & 1 \ 0 & 0 & 0 \ 0 & 0 & 0 \end{bmatrix}$

The last nonzero row has a leading coefficient of 0, which means that the vectors are linearly dependent.



c. The matrix formed by the given vectors is:
$\begin{bmatrix} 1 & 1 & 0 \ 0 & 1 & 1 \ 1 & 0 & -1 \end{bmatrix}$

We can perform row echelon form on this matrix, which gives us:
$\begin{bmatrix} 1 & 0 & -1 \ 0 & 1 & 1 \ 0 & 0 & 0 \end{bmatrix}$

The last nonzero row has a leading coefficient of 1, which means that the vectors are linearly independent.



d. The matrix formed by the given vectors is:
$\begin{bmatrix} 1 & 2 & 0 \ 3 & 2 & 1 \end{bmatrix}$

By calculating the determinant of the matrix, we have:
$det(\begin{bmatrix} 1 & 2 & 0 \ 3 & 2 & 1 \end{bmatrix})= (12 - 30) - (21 - 20) + (01 - 01)=0$, which means that the vectors are linearly dependent, as the determinant is zero.

Alternatively, we can see that vector x3 is a linear combination of vector x1 and x2, as 0x1 + 1x2 = x3.

Therefore, the given set of vectors are linearly dependent.

**Collaborators and resources:**

- [How to write matrices in Latex ? matrix, pmatrix, bmatrix, vmatrix, Vmatrix](https://www.math-linux.com/latex-26/faq/latex-faq/article/how-to-write-matrices-in-latex-matrix-pmatrix-bmatrix-vmatrix-vmatrix)

###Question 3 (10 points)
Given 

$x_1 = \begin{bmatrix} 1 \\ 2 \\ 0 \end{bmatrix}$, $x_2 = \begin{bmatrix} 3 \\ 1 \\ 1 \end{bmatrix}$, $x_3 = \begin{bmatrix} 4 \\ -7 \\ 3 \end{bmatrix}$, 

determine whether $x_3$ belongs to Span{$x_1, x_2$}

**Your response:**

Detrmine whether $x_3$ belongs to Span{$x_1, x_2$} essentially means check if $x_3$ can be written as a linear combination of $x_1$ and $x_2$.
In other words, we need to check if there exist scalars $a$ and $b$ such that $x_3 = ax_1 + bx_2$.

We can set up the following system of equations:

$4 = a + 3b$


$-7 = 2a + b$


$3 = 0a + b$

By solving this system of equations, we can find that $a = -7/3$ and $b = 3/3$, which means that $x_3$ can be written as a linear combination of $x_1$ and $x_2$:
$x_3 = -7/3x_1 + 3/3x_2$

Therefore, $x_3$ belongs to Span{$x_1, x_2$}.

**Collaborators and resources:**

Not applicable

#Part B (Solve with code)

You should solve the questions in Part B by writing computer code in `Python`, using the `numpy` and `matplotlib` modules.
"""

# execute this cell to begin
import numpy as np
import matplotlib.pyplot as plt

# if you execute this cell, then you will get a description of
# how the array command works, with examples

help(np.array)

"""Also, you may find it useful to use the Python `try` and `except` statements as you test whether certain operations are defined.

###Question 4 (9 points)

If possible, calculate the inner (dot) product of the following vectors:

1. $a = \begin{bmatrix} 2 \\ 1 \\ 3 \\ 0 \end{bmatrix}, b = \begin{bmatrix} -1 \\ 2 \\ 0 \\ 5\end{bmatrix}$ \

2. $a = \begin{bmatrix} 0 \\ -2 \\ 1 \\ 3 \end{bmatrix}, b = \begin{bmatrix} 6 \\ 5 \\\end{bmatrix}$ \

3. $a = \begin{bmatrix} 5 \\ 1 \\ -7 \\ 1 \end{bmatrix}, b = \begin{bmatrix} 2 \\ 1 \\ -3 \\ 0 \end{bmatrix}$ \
"""

# write your solution here

# Question 1

import numpy as np

a = np.array([2, 1, 3, 0])
b = np.array([-1, 2, 0, 5])

inner_product_q1 = np.dot(a, b)
print(inner_product_q1)


# Question 2

print("For this set of vector, it is not possible to calculate the dot product between the two given vectors because they are not of the same dimensions.")
print("The dot product of two vectors can only be calculated if they are both of the same dimension (number of elements in the vector) and the result is a scalar.")


# Question 3

import numpy as np

a = np.array([5, 1, -7, 1])
b = np.array([2, 1, -3, 0])

inner_product_q3 = np.dot(a, b)
print(inner_product_q3)

"""**Collaborators and resources:**

- [How to calculate dot product of two vectors in Python?](https://www.geeksforgeeks.org/how-to-calculate-dot-product-of-two-vectors-in-python/)

### Question 5 (5 points)

Compute the distance between

$x = \begin{bmatrix} 1 \\ 2 \\ 3 \end{bmatrix}, y = \begin{bmatrix} -1 \\ -1 \\ 0 \end{bmatrix}$

First compute the answers component-wise (i.e., using the algebraic formula). Then confirm your answer with `numpy`'s linear algebra libraries.
"""

# write your solution here

import numpy as np

x = np.array([1, 2, 3])
y = np.array([-1, -1, 0])

distance = np.sqrt(np.sum((x - y) ** 2))

print("Distance between x and y:", distance)


# Confirmation of answer with NumPy linalg.norm

import numpy as np

x = np.array([1, 2, 3])
y = np.array([-1, -1, 0])

distance = np.linalg.norm(x - y)

print("Distance between x and y:", distance)

"""**Collaborators and resources:**

- [numpy.linalg.norm](https://numpy.org/doc/stable/reference/generated/numpy.linalg.norm.html)

###Question 6 (15 points)

Verify the following vector properties emprically. Generate random column vectors and verify that the given properties hold true for them. you can use numpy to generate a random vector:

a. ${\bf u} + {\bf v} = {\bf v} + {\bf u}$

b. $({\bf u} + {\bf v}) + {\bf w} = {\bf u} + ({\bf v} + {\bf w})$

c. ${\bf u} + ({\bf -u}) = {\bf -u} + {\bf u} = {\bf 0}$

d. $1{\bf u} = {\bf u}$

e. $({\bf u}+{\bf v})^\top = {\bf u}^\top + {\bf v}^\top$ (remember that the ${}^\top$ symbol denotes the transpose operation)
"""

# write your solution here

# a.

import numpy as np

# Generate two random column vectors of size 3
u = np.random.rand(3, 1)
v = np.random.rand(3, 1)

# Add the vectors in both orders
add_uv = u + v
add_vu = v + u

# Check if the results are the same
if np.array_equal(add_uv, add_vu):
    print("The property holds true for the given vectors.")
else:
    print("The property does not hold true for the given vectors.")

# b. 

import numpy as np

# Generate three random column vectors of size 3
u = np.random.rand(3, 1)
v = np.random.rand(3, 1)
w = np.random.rand(3, 1)

# Add the vectors in both orders
add_u_v_w1 = (u + v) + w
add_u_v_w2 = u + (v + w)

# Check if the results are the same
if np.array_equal(add_u_v_w1, add_u_v_w2):
    print("The property holds true for the given vectors.")
else:
    print("The property does not hold true for the given vectors.")

# c.

import numpy as np

# Generate a random column vector
u = np.random.rand(3, 1)

# Create -u by negating u
minus_u = -u

# Add u and -u
sum = u + minus_u

# Check if the resulting vector is the zero vector
print(np.allclose(sum, np.zeros((3, 1))))

# d.

import numpy as np

# Generate a random column vector of size 3
u = np.random.rand(3, 1)

# Multiply the vector by 1
v = 1 * u

# Check if the vectors are equal
if (u == v).all():
    print("The property holds true for this vector")
else:
    print("The property does not hold true for this vector")

# e. 

import numpy as np

# Generate random column vectors u and v
u = np.random.rand(3, 1)
v = np.random.rand(3, 1)

# Compute (u + v)^T and u^T + v^T
lhs = (u + v).T
rhs = u.T + v.T

# Compare the results
if np.allclose(lhs, rhs):
    print("The property holds true for the given vectors.")
else:
    print("The property does not hold true for the given vectors.")

"""**Collaborators and resources:**

Not applicable

###Question 7 (10 points)

Solve the following system of linear equations geometrically. That is, use matplotlib to plot the equations and find the values of $x$ and $y$:


  $3x + 3y = 15$ \
  $4x + 3y = 18$
"""

import matplotlib.pyplot as plt
import numpy as np

# Define the coefficients of the equations
a1, b1, c1 = 3, 3, 15
a2, b2, c2 = 4, 3, 18

# Generate x and y values for the lines
x = np.linspace(-10, 10, 100)
y1 = (c1 - a1*x) / b1
y2 = (c2 - a2*x) / b2

# Plot the lines
plt.plot(x, y1, label='3x + 3y = 15')
plt.plot(x, y2, label='4x + 3y = 18')

# Add a legend
plt.legend()

# Add grid
plt.grid()

# Add x and y axis labels
plt.xlabel('x')
plt.ylabel('y')

#Find the intersection point
intersection_x = (c1*b2 - c2*b1) / (a1*b2 - a2*b1)
intersection_y = (c1*a2 - c2*a1) / (b1*a2 - b2*a1)

#Mark the intersection point
plt.scatter(intersection_x, intersection_y, color='red', marker='o')

# Show the plot
plt.show()

"""The intersection point, which is the solution to the system of equations, with x = 1 and y = 2.

**Collaborators and resources:**

Not applicable

# Part C: Recap of lectures and reading

###Question 8 (2 points)

What's one thing you found interesting in the required reading and viewing assignment?

**Your response:**

In computer graphics, matrices are used for tasks such as transforming 3D coordinates into 2D screen coordinates, and for representing rotations and translations of objects in 3D space.

### Question 9 (2 points)

What's one thing you found confusing in the required reading and viewing assignment?

**Your response:**

How to determine whether a set of vectors are in the state of linearly independent or linearly dependent?

### Question 10 (1 point)

What topic(s) would you like to see covered in future discussion sections?

**Your response:**

In-depth examples of using Python for linear algebra calculations.
"""